name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ gcc libgtest-dev


    - name: Install ARM GCC toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi

    - name: Configure and build (ARM toolchain)
      run: |
        python build.py --toolchain toolchains/gcc-arm-none-eabi.cmake

    - name: Run Unit Tests (host build)
      run: |
        python build.py
        cd build
        ctest --output-on-failure